server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: usage-service
          uri: lb://USAGE-SERVICE
          predicates:
            - Path=/usage-service/**
          filters:
            - RewritePath=/usage-service/(?<segment>.*), /$\{segment}
        - id: settlement-service
          uri: lb://SETTLEMENT-SERVICE
          predicates:
            - Path=/settlement-service/**
          filters:
            - RewritePath=/settlement-service/(?<segment>.*), /$\{segment}
